config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'users/new'
  get 'users/create'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  get 'about/index'
  get 'login/index'
  get 'register/index'
  get 'follow/index'
  get 'logout/index'
  get 'order/index'
  get 'edit/index'

  resources :users, only: [:new, :create]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   get 'welcome', to: 'sessions#welcome'
   get 'authorized', to: 'sessions#page_requires_login'
   get 'users/out' , to: 'sessions#destroy'

 
  root 'sessions#welcome'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/edit_controller.rb
class EditController < ApplicationController
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username,        
   :password,:f_name,:l_name,:address,:tele))
   session[:user_id] = @user.id
   redirect_to '/welcome'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", sessions_welcome_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          <%= image_tag 'food.png', style: "width:100%"%>
          
          <div class=box>
          </br>
          <center><p><font size='+2'>About</font></p></center>
          <p><font size='+2'>Links</font></p>
          <a href="https://drive.google.com/drive/folders/1mFKsHOrahTIc51FrI9wmz22118xwNr-R" target="_blank">Proposal</a>
          <a href="https://gitlab.com/5910680361/arhan" target="_blank">git repository</a>
          <a href="https://www.pivotaltracker.com/n/projects/2407180" target="_blank">pivotal tracker</a>
          <p><font size='+2'>User Stories</font></p>
          <div class="page-content">
          <center>
          <%= image_tag 'us.png' %>
          
          </center>
          </div>



          
          
          
          </div>
          </div>
          </div>
  
</body>
</html>

app/views/edit/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }
  p.margin {
  margin-left:100px;
}
p.marginmore {
  margin-left:350px;
}

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", sessions_welcome_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Order Food", order_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Follow Food List", follow_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Edit Profile", edit_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Logout", '/users/out', method: :get%> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          
          <%= image_tag 'food.png', style: "width:100%"%>         
          <div class=box>
          </br>
          <center><p><font size='+2'>Edit Profile</font></p></center>
          <center><font size='+2'>
          <% if logged_in? %>
          
          Your current profile</br>
          <%end%>
          </center>
          <p class=marginmore>
          <% if logged_in? %>
          username :
          <%= 
              current_user.username
          %></br>
          first name :
          <%= 
              current_user.f_name
          %></br>
          last name :
          <%= 
              current_user.l_name
          %></br>
          address :
          <%= 
              current_user.address
          %></br>
          telephone number :
          <%= 
              current_user.tele
          %></br>
          
          <%end%>
        
          </font>
          </p>
          

          
          
         
          </div>
          </div>
  
</body>
</html>

app/views/follow/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", sessions_welcome_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Order Food", order_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Follow Food List", follow_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Edit Profile", edit_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Logout", '/users/out', method: :get%> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          
          <%= image_tag 'food.png', style: "width:100%"%>         
          <div class=box>
          </br>
          <center><p><font size='+2'>Follow Food List</font></p></center>


          
          
         
          </div>
          </div>
  
</body>
</html>

app/views/login/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", welcome_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Register", register_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Login", login_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          
          <%= image_tag 'food.png', style: "width:100%"%>         



          
          
         
          </div>
          </div>
  
</body>
</html>

app/views/logout/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", welcome_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Register", register_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Login", login_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          
          <%= image_tag 'food.png', style: "width:100%"%>         



          
          
         
          </div>
          </div>
  
</body>
</html>

app/views/order/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", sessions_welcome_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Order Food", order_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Follow Food List", follow_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Edit Profile", edit_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Logout", '/users/out', method: :get%></a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          
          <%= image_tag 'food.png', style: "width:100%"%>         
          <div class=box>
          </br>
          <center><p><font size='+2'>Order Food</font></p></center>


          
          
         
          </div>
          </div>
  
</body>
</html>

app/views/register/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", welcome_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Register", register_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          
          <%= image_tag 'food.png', style: "width:100%"%>  
          
          <div class=box>
          </br>
          <center><p><font size='+2'>Register</font></p></center>
          <%= form_for @user do |f|%>
            <%= f.label :username%><br>
            <%= f.text_field :username%><br>
            <%= f.label :password%><br>
            <%= f.password_field :password%><br>
            <%= f.submit %>
          <%end%>

        



          
          
         
          </div>
          </div>
  
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.box {       
        background-color:#000000;
        color:white;
        font-weight:bold;
        margin:0px auto;
        height:1000px ;        
        width: 900px ;
    }
a:link, a:visited {
      background-color: #f44336;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }
    
a:hover, a:active {
      background-color: red;
    }
.page-content img {
      max-width: 100% ;
      height: auto;
      margin-bottom:20px;
  }

</style>

<body>

          <div class="w3-top">
          <div class="w3-bar w3-black w3-card">
          
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Home", welcome_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Register", register_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "Login", login_index_path %> </a>
          <a class="w3-bar-item w3-button w3-padding-large"><%= link_to "About", about_index_path %> </a>
          
          </div>
          </div>

          <div class="w3-content" style="max-width:2000px;margin-top:46px">
          <div class="container">
          
          <%= image_tag 'food.png', style: "width:100%"%>    
          
          <div class=box>
          </br>
          <center><p><font size='+2'>Welcome to our website!</font></p></center>
          <center>
          <%= image_tag 'op.png' %>
          
          </center>


          
          
         
          </div>
          </div>
  
</body>
</html>