config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :trips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "application#home"

  # get 'current_user' => "users#current_user"

   resources :users, only: [:new, :show] do
    # nested resource for trips
     resources :trips, only: [:show, :index]
   end


    # nested resource for reviews
    resources :users, only: [:new, :show] do
      resources :reviews, only: [:new, :edit, :show, :index]
   end
  resources :users
  resources :meals
  resources :orders, only: [:new, :destroy]

  get '/auth/facebook/callback' => 'sessions#create'

  get '/auth/failure' => 'sessions#failure'

  get '/most_popular', to: 'meals#most_popular'

  get '/signin', to: 'sessions#signin'
  post '/signin', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

   get '/add_meal', to: 'orders#add_meal'
  get'/checkout', to: 'trips#checkout'
  get 'about/index'
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def new
    @review = Review.new #(user_id: params[:user_id])
  end

  def create
     @review = Review.new(review_params)
    if !params[:user_id] || !logged_in?
      flash[:alert] = "Must be signed in to create review"
      redirect_to root_path
    elsif is_admin?
      flash[:alert] = "Admin can't create reviews!"
      redirect_to root_path
    elsif  params[:user_id]

      @user = User.find_by(id: params[:id])
      @review = @user.reviews.build(review_params)
      if @review.save
        respond_to do |format|
          # format.html { redirect_to reviews_path }
          format.json { render json: @review, status: 201}
        end

       else
        render :new
      end

  else
      @user = current_user
      @review = @user.reviews.build(review_params)
       if @review.save
         respond_to do |format|
           # format.html { redirect_to reviews_path }
           format.json { render json: @review, status: 201}
         end
       else
         render :new
       end
  end
end

  def show
    @review = Review.find_by(id: params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @review}
    end
  end

  def edit

    @review = Review.find(params[:id])
    if !is_admin? && current_user == @review.user
      if params[:user_id]
        user = User.find_by(id: params[:user_id])
        @review = user.reviews.find_by(id: params[:id])
        redirect_to user_reviews_path(user), alert: "Review not found" if @review.nil?
      else
        @review = Review.find(params[:id])
      end
    else
      flash[:alert] = "You can't edit this review!"
      redirect_to reviews_path
    end
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    @user = @review.user
    respond_to do |format|
      format.html { redirect_to user_reviews_path(@user) }
      format.json { render json: @review}
    end
    # redirect_to user_reviews_path(@user)
  end

  def index
    # binding.pry
    # puts  ENV['FACEBOOK_SECRET'] + 111

    if params[:user_id]
      @reviews = User.find(params[:user_id]).reviews
   else
      @reviews = Review.all
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @reviews}
    end

  end

  def destroy
    @review = Review.find(params[:id])

    if !is_admin? && current_user == @review.user
      @review.destroy
      redirect_to reviews_path
    else
      redirect_to reviews_path
      flash[:alert] = "You can't delete this review!"
  end
end


  private

  def review_params
    params.require(:review).permit(:title, :comment, :date_posted, :user_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_errors.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@review.errors.count, "error") %>
      prohibited this review from being saved:
    </h2>

    <ul>
    <% @review.errors.full_messages.each do |msg| %>
    <% if @review.errors.any? %>
    <li><%= msg %></li>
    <% end %>
    </ul>

    </div>
    <% end %>
    <% end %>

app/views/reviews/_form.html.erb
<%= render 'errors' %>

    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <%= f.label :comment %>
    <%= f.text_area :comment %> <br>
    <%= f.label :date_posted %>
    <%= f.date_field :date_posted %> <br>

    <%= f.submit :html=> { class: 'reset' }  %>

app/views/reviews/edit.html.erb
<%= form_for @review do |f| %>
<p class="form-title">Edit Your Review</p>
<%= render 'form', :f => f %>

<% end %>

app/views/reviews/index.html.erb
<div class="trip">
<!-- SECRET <%= ENV['FACEBOOK_SECRET'] %> -->
<h1>reviews -  <%= link_to "new", new_user_review_path(current_user) if current_user  %></h1> <br>
<h2></h2> <br>
<h3><%= "Sign In to Leave A Review" if !current_user %></h3>

<br>
  <% if @reviews %>
<% @reviews.each do |review|%>

  <h4 ><%= link_to review.title, user_review_path(review.user, review) %>  <%= link_to "| Edit Review", edit_user_review_path(review.user, review) if logged_in? %>  <%=  link_to " | Delete", review, method: :delete if logged_in? %> </h4>
  <p><%= review.comment %></p>
  <p>Date: <%= (review.date_posted).strftime("%b %d, %Y") %></p>
  <p>by: <%= link_to review.user.named, user_reviews_path(review.user) %></p> <br><br>
<% end %>

<% end %>
</div>

app/views/reviews/new.html.erb
<%= form_for @review, :html=> { class: 'form-review' } do |f|%>
<p class="form-title">Write A Review</p>
<%= render 'form', :f => f %>

<% end %>

<div id="reviewResult" style="text-align: center">
  <h2 id="reviewTitle"></h2>
  <p id="reviewComment"></p>
  <p id="reviewDate"></p>
  <p id="reviewUser"></p>
</div>

app/views/reviews/show.html.erb
<div class="review">
  <h1>Review No. <%= @review.id%> </h1> <br>
  <p>Date: <%= (@review.date_posted).strftime("%b %d, %Y") %></p>
  <<p>By: <%=  @review.user.named%>  <%= link_to "|| Edit Review", edit_user_review_path(@review.user, @review) if logged_in? %> <%= link_to " || Delete", @review, method: :delete if logged_in? %></<p>
  <!-- Line below was in original rails project -->
   <!--<p>By: <%= link_to @review.user.named, user_path(@review.user) %>  <%= link_to "|| Edit Review", edit_user_review_path(@review.user, @review) if logged_in? %> <%= link_to " || Delete", @review, method: :delete if logged_in? %></p> -->
  <h2><%= @review.title%></h2>
  <h3><%= @review.comment %></h3> <br> <br>

  <h3><%= link_to "Create A New Review", new_user_review_path(@review.user)  %></h3>
</div>