config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :trips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "application#home"

  # get 'current_user' => "users#current_user"

   resources :users, only: [:new, :show] do
    # nested resource for trips
     resources :trips, only: [:show, :index]
   end


    # nested resource for reviews
    resources :users, only: [:new, :show] do
      resources :reviews, only: [:new, :edit, :show, :index]
   end
  resources :users
  resources :meals
  resources :orders, only: [:new, :destroy]

  get '/auth/facebook/callback' => 'sessions#create'

  get '/auth/failure' => 'sessions#failure'

  get '/most_popular', to: 'meals#most_popular'

  get '/signin', to: 'sessions#signin'
  post '/signin', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

   get '/add_meal', to: 'orders#add_meal'
  get'/checkout', to: 'trips#checkout'
  get 'about/index'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<body>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Arhan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Libre+Baskerville|Roboto:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,600">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="login">
            <ul>
              <li><%= login_helper %></li>
            </ul>
        </div>
        <div class="logo">
          <a href="<%= root_url %>">Arhan</a>
        </div>
        <nav>
          <ul>
            <li><%= link_to "menu", meals_path%></li>
            
             <li><%= link_to "about", about_index_path%></li>
            
            <l1> <%= admin_items %></l1>
          </ul>
        </nav>
      </div>
    </header>
    
      <%= flash_helper %>
    <%= yield %>

    
  </body>
</html>